#!/bin/bash
set -e
set -f

USERNAME="telerising"

if [[ -z "${TIMEZONE}" ]]; then
  TIMEZONE="Europe/Berlin"
fi

if [[ -z "${GROUP_ID}" ]]; then
  GROUP_ID="100"
fi

if [[ -z "${USER_ID}" ]]; then
  USER_ID="99"
fi

if [[ -z "${UPDATE}" ]]; then
  UPDATE="yes"
fi

if [[ -z "${PROVIDER}" ]]; then
  PROVIDER="zattoo.com"
fi

if [[ -z "${SERVER}" ]]; then
  SERVER="fr5-0"
fi

if [[ -z "${NETWORK_DEVICE}" ]]; then
  NETWORK_DEVICE="eth0"
fi

if [[ -z "${FFMPEG_HOST_LOCATION}" ]]; then
  FFMPEG_HOST_LOCATION="\/usr\/bin\/ffmpeg"
fi

if [[ ! -f /telerising/zattoo.pl ]] || [[ "${UPDATE}" = "yes" ]]; then
  /usr/local/bin/telerising.update
fi

ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

echo "${USERNAME}:x:${USER_ID}:${GROUP_ID}:$USERNAME}:/:/sbin/nologin" >> /etc/passwd
echo "${USERNAME}:!::0:::::" >> /etc/shadow

if ! getent group ${GROUP_ID}; then
  echo "${USERNAME}:x:${GROUP_ID}:" >> /etc/group
fi

chown -R ${USER_ID}:${GROUP_ID} /telerising
chown -R ${USER_ID}:${GROUP_ID} /tmp
chmod -R 775 /telerising
chmod -R 777 /tmp

if [[ -z "${LOGIN}" ]] || [[ -z "${PASSWORD}" ]]; then
  echo "ERROR, you need to setup USERNAME and PASSWORD first"
fi

sed "s/XXX/${PROVIDER}/g;s/YYY/${LOGIN}/g;s/ZZZ/${PASSWORD}/g;s/XYZ/${SERVER}/g;s/AAA/${NETWORK_DEVICE}/g;s/BBB/${FFMPEG_HOST_LOCATION}/g" /etc/userfile.json 2> /dev/null > /telerising/userfile.json

su -s /bin/bash -c "TERM=xterm /usr/local/bin/telerising.process" ${USERNAME}
