#!/bin/bash
set -e
set -f

USERNAME="telerising"

if [[ -z "${TIMEZONE}" ]]; then
  TIMEZONE='Europe/Berlin'
fi

if [[ -z "${GROUP_ID}" ]]; then
  GROUP_ID='100'
fi

if [[ -z "${USER_ID}" ]]; then
  USER_ID='99'
fi

if [[ -z "${UPDATE}" ]]; then
  UPDATE='yes'
fi

if [[ -z "${PROVIDER}" ]]; then
  PROVIDER='zattoo.com'
fi

if [[ -z "${YOUTH_PROTECTION_PIN}" ]]; then
  YOUTH_PROTECTION_PIN='1234'
fi

if [[ -z "${SERVER}" ]]; then
  SERVER='fr5-0'
fi

if [[ -z "${NETWORK_DEVICE}" ]]; then
  NETWORK_DEVICE='eth0'
fi

if [[ -z "${SSL_MODE}" ]]; then
  SSL_MODE='0'
fi

if [[ -z "${FFMPEG_HOST_LOCATION}" ]]; then
  FFMPEG_HOST_LOCATION='/usr/bin/ffmpeg'
fi

#### Default Settings
if [[ -z "${PLATFORM}" ]]; then
  PLATFORM='hls5'
fi

if [[ -z "${BW}" ]]; then
  BW='8000'
fi

if [[ -z "${PROFILE}" ]]; then
  PROFILE='1'
fi

if [[ -z "${AUDIO2}" ]]; then
  AUDIO2='false'
fi

if [[ -z "${DOLBY}" ]]; then
  DOLBY='false'
fi

if [[ -z "${IGNORE_MAXRATE}" ]]; then
  IGNORE_MAXRATE='false'
fi

if [[ -z "${FFMPEG_LOGLEVEL}" ]]; then
  FFMPEG_LOGLEVEL='fatal'
fi

## VOD
if [[ -z "${ONDEMAND}" ]]; then
  ONDEMAND='false'
fi



if [[ ! -f /telerising/zattoo.pl ]] || [[ "${UPDATE}" = "yes" ]]; then
  /usr/local/bin/telerising.update
fi

ln -fs /usr/share/zoneinfo/${TIMEZONE} /etc/localtime
dpkg-reconfigure -f noninteractive tzdata

echo "${USERNAME}:x:${USER_ID}:${GROUP_ID}:$USERNAME}:/:/sbin/nologin" >> /etc/passwd
echo "${USERNAME}:!::0:::::" >> /etc/shadow

if ! getent group ${GROUP_ID}; then
  echo "${USERNAME}:x:${GROUP_ID}:" >> /etc/group
fi

chown -R ${USER_ID}:${GROUP_ID} /telerising
chown -R ${USER_ID}:${GROUP_ID} /tmp
chmod -R 775 /telerising
chmod -R 777 /tmp

if [[ -z "${LOGIN}" ]] || [[ -z "${PASSWORD}" ]]; then
  echo "ERROR, you need to setup USERNAME and PASSWORD first"
fi

## If no Adress is given, use Interface instead Hostname / IP
if [[ -z "${ADDRESS}" ]]; then
  echo""
  echo "No Ip or Hostname set, using Interface $NETWORK_DEVICE"
  echo""
  jq --arg PROVIDER $PROVIDER --arg LOGIN $LOGIN --arg PASSWORD $PASSWORD --arg NETWORK_DEVICE $NETWORK_DEVICE --arg SERVER $SERVER --arg FFMPEG_HOST_LOCATION $FFMPEG_HOST_LOCATION --arg SSL_MODE $SSL_MODE --arg YOUTH_PROTECTION_PIN $YOUTH_PROTECTION_PIN --arg PLATFORM $PLATFORM --arg BW $BW --arg PROFILE $PROFILE --arg AUDIO2 $AUDIO2 --arg DOLBY $DOLBY --arg IGNORE_MAXRATE $IGNORE_MAXRATE --arg FFMPEG_LOGLEVEL $FFMPEG_LOGLEVEL --arg ONDEMAND $ONDEMAND '{
      "provider": $PROVIDER,
      "login": $LOGIN,
      "password": $PASSWORD,
      "interface": $NETWORK_DEVICE,
      "server": $SERVER,
      "ffmpeg_lib": $FFMPEG_HOST_LOCATION,
      "port": "8180",
      "ssl_mode": $SSL_MODE,
      "youth_protection_pin": $YOUTH_PROTECTION_PIN,
      "platform": $PLATFORM,
      "bw": $BW,
      "profile": $PROFILE,
      "audio2": $AUDIO2,
      "dolby": $DOLBY,
      "ignore_maxrate": $IGNORE_MAXRATE,
      "loglevel": $FFMPEG_LOGLEVEL,
      "ondemand": $ONDEMAND
    }
  ' < /etc/userfile.json > /telerising/userfile.json
fi

## If Adress is given, use IP / Hostname instead Interface
if [[ "${ADDRESS}" ]]; then
  echo""
  echo "Hostname / IP $ADDRESS has ben entered, ignoring Interface $NETWORK_DEVICE"
  echo""
  jq --arg PROVIDER $PROVIDER --arg LOGIN $LOGIN --arg PASSWORD $PASSWORD --arg ADDRESS $ADDRESS --arg SERVER $SERVER --arg FFMPEG_HOST_LOCATION $FFMPEG_HOST_LOCATION --arg SSL_MODE $SSL_MODE --arg YOUTH_PROTECTION_PIN $YOUTH_PROTECTION_PIN --arg PLATFORM $PLATFORM --arg BW $BW --arg PROFILE $PROFILE --arg AUDIO2 $AUDIO2 --arg DOLBY $DOLBY --arg IGNORE_MAXRATE $IGNORE_MAXRATE --arg FFMPEG_LOGLEVEL $FFMPEG_LOGLEVEL --arg ONDEMAND $ONDEMAND '{
      "provider": $PROVIDER,
      "login": $LOGIN,
      "password": $PASSWORD,
      "address": $ADDRESS,
      "server": $SERVER,
      "ffmpeg_lib": $FFMPEG_HOST_LOCATION,
      "port": "8180",
      "ssl_mode": $SSL_MODE,
      "youth_protection_pin": $YOUTH_PROTECTION_PIN,
      "platform": $PLATFORM,
      "bw": $BW,
      "profile": $PROFILE,
      "audio2": $AUDIO2,
      "dolby": $DOLBY,
      "ignore_maxrate": $IGNORE_MAXRATE,
      "loglevel": $FFMPEG_LOGLEVEL,
      "ondemand": $ONDEMAND
    }
  ' < /etc/userfile.json > /telerising/userfile.json
fi

su -s /bin/bash -c "TERM=xterm /usr/local/bin/telerising.process" ${USERNAME}
